spring:
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=problems
    username:
    password:
  jpa:
    hibernate:
      dd-auto: none
    show-sql: false

dgs:
  graphql:
    schema-locations:
      - classpath*:schema/**/*.graphql
      - classpath*:schema/**/*.gql
